"""add users updated_at

Revision ID: 4f198960f636
Revises: e50484caedcc
Create Date: 2026-09-26 17:39:15.502705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f198960f636'
down_revision: Union[str, Sequence[str], None] = 'e50484caedcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 【为什么必须带 server_default=now()】
    # 这一列是 NOT NULL，而 users 表里可能已经有行。若不给数据库侧默认值，
    # PostgreSQL 会因"已有行无法满足非空约束"直接拒绝 ALTER TABLE。
    # 给了 server_default 之后，存量行会被一次性回填为当前时间。
    # （本次执行时库里已有 1 个种子 admin，正是靠它才没报错。）
    #
    # 注意：DDL 上的 server_default 与模型里的 onupdate=func.now() 分工不同 ——
    # 前者只管"加列时怎么填历史数据"，后者管"以后每次 UPDATE 自动刷新时间"。
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='用户信息最近更新时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
