"""init documents and document chunks

Revision ID: b113db5ee4e1
Revises: 
Create Date: 2026-09-05 15:37:22.398482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# 1) 增加一条 import: 显式导入 pgvector 扩展，解决迁移脚本中 VECTOR 类型未解析爆红
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'b113db5ee4e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    upgrade 函数的作用是让变更生效，会实际影响数据库表结构。
    """
    # 2) 在 upgrade() 函数最开头加一行启用 pgvector 扩展：
    # 镜像 pgvector/pgvector:pg16 已自带，无需额外安装，但建表前必须激活该插件以支持 vector 数据类型
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='文档全局唯一UUID主键'),
    sa.Column('name', sa.String(length=512), nullable=False, comment='文档原始文件名称'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件内容的 SHA-256 哈希值，用于幂等去重'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='文件 MIME 媒体类型'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='文件大小（字节 Byte）'),
    sa.Column('storage_provider', sa.String(length=32), nullable=False, comment='底层对象存储提供商标识'),
    sa.Column('cos_bucket', sa.String(length=128), nullable=False, comment='腾讯云 COS 存储桶名称'),
    sa.Column('cos_object_key', sa.String(length=512), nullable=False, comment='对象在 COS 中的全路径 Key'),
    sa.Column('cos_region', sa.String(length=64), nullable=False, comment='COS 存储桶所属地域'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='文档生命周期处理状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='解析/索引失败时的错误信息堆栈'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='切片全局唯一UUID主键'),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='所属文档ID（外键级联删除）'),
    sa.Column('content', sa.Text(), nullable=False, comment='切片纯文本正文内容'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='文本嵌入向量（与配置维度对齐）'),
    sa.Column('page_no', sa.Integer(), nullable=True, comment='文档所在物理页码'),
    sa.Column('section_path', sa.String(length=1024), nullable=True, comment='标题层级面包屑路径'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切片顺序序号'),
    sa.Column('chunk_hash', sa.String(length=32), nullable=False, comment='切片文本MD5哈希'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='扩展元数据（JSONB存储）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='切片入库创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_hash'), 'document_chunks', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    downgrade 是 upgrade 的反操作，用于回退库表结构的变更。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

    # 3) 在 downgrade() 函数最后一行删除 pgvector 扩展：
    # 彻底回滚当前版本时，连带移除 vector 插件扩展
    op.execute("DROP EXTENSION IF EXISTS vector")