"""add auth tables and permission tags

Revision ID: e50484caedcc
Revises: d454894ea042
Create Date: 2026-09-25 21:39:53.613052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50484caedcc'
down_revision: Union[str, Sequence[str], None] = 'd454894ea042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False, comment='角色全局唯一UUID主键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色唯一名称，如 admin / user / hr'),
    sa.Column('description', sa.String(length=256), nullable=False, comment='角色用途说明'),
    sa.Column('permission_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='角色持有的权限标签数组；* 表示通配'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='角色创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户全局唯一UUID主键'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名，全局唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 密码哈希，禁止存明文'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='界面展示名称'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='账号状态：active 可登录 / disabled 已停用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='用户创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('conversations', sa.Column('user_id', sa.UUID(), nullable=True, comment='会话归属用户 ID；用户被删后置 NULL，会话保留'))
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # 【手工命名外键】本项目未配置 naming_convention（见 alembic/env.py），autogenerate 会生成
    #   op.create_foreign_key(None, ...) 让 PostgreSQL 自行取名，downgrade 时便无从 drop。
    #   这里显式命名为 PostgreSQL 的默认格式，保证迁移可逆。
    op.create_foreign_key(
        'conversations_user_id_fkey', 'conversations', 'users',
        ['user_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('documents', sa.Column('permission_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='数据权限标签数组；空数组视为公开可检索'))
    op.add_column('documents', sa.Column('created_by', sa.UUID(), nullable=True, comment='上传者用户 ID；用户被删后置 NULL，文档历史保留'))
    # GIN 索引：支撑 permission_tags && user_tags 的数组重叠过滤。
    #   【为什么它能被 autogenerate 检出】因为已在 Document.__table_args__ 中显式声明 ——
    #   只在迁移里写 op.execute("CREATE INDEX ...") 而模型不声明的话，
    #   下一次 autogenerate 会把它当成"库里多出来的对象"生成 drop_index 删掉。
    op.create_index('ix_documents_permission_tags', 'documents', ['permission_tags'], unique=False, postgresql_using='gin')
    op.create_foreign_key(
        'documents_created_by_fkey', 'documents', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 【手工调整了顺序】autogenerate 把 drop_table('users') 排在两个外键删除【之前】，
    #   而 documents / conversations 的外键正指向 users，PostgreSQL 会因存在依赖而报错。
    #   必须先拆掉这两个外键，再删 users 表 —— 否则 downgrade 直接跑不通。
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_created_by_fkey', 'documents', type_='foreignkey')
    op.drop_index('ix_documents_permission_tags', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'permission_tags')
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_column('conversations', 'user_id')
    op.drop_table('user_roles')
    # users 最后删：此时已没有任何外键指向它
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
